### ISSUE TITLE
Figure out a standard for sending client info in on GameConnection::onConnectRequest

### ISSUE THREAD

**Issue by TheBlackParrot** [TheBlackParrot/blockland-preferences#4]
considering `"BPM" [APIVersion(?)] [BPMClientVersion] [BPMClientName]"`
e.g. `"BPM dev0 1.0.0 DefaultClient"`, and out of development `"BPM 1 1.0.0 DefaultClient"`

the first 2 are really the only necessary things we should probably get, honestly

**Comment by nightkr** [comment]
I'd say "BPM [APIVersion] [APIDraft?]". So the 1.0 release would say "BPM 1", while the 4th draft revision of the second revision of the protocol would say "BPM 2 4". Perhaps also add semver for APIVersion?

**Comment by TheBlackParrot** [comment]
yeah, that would be better

**Comment by dpendic** [comment]
I've been thinking of porting over the SemVer library I wrote in PHP, it wouldn't be hard. Could help with comparing versions
