### ISSUE TITLE
Pref indexing

### ISSUE THREAD

**Issue by dpendic** [TheBlackParrot/blockland-preferences#7]
Find some way to identify preferences exactly. If two add-ons have a pref named "Timeout" and we want to update the value, we need a better way to communicate which pref is being updated.

I suggest just sending the object id, but I didn't want to make any changes to interaction.cs without talking about it first.

**Comment by TheBlackParrot** [comment]
The variable itself is sent along with everything else, you could probably use that

**Comment by dpendic** [comment]
Alright, then in that case there needs to be protection against registering two prefs for the same variable.

**Comment by TheBlackParrot** [comment]
You could loop through prefs and see if it's already registered to a specific variable, but that'd be rather exhaustive... hm.  
I was wanting to (initially) create either a ScriptGroup or a SimSet for each category/addon, and add prefs (ScriptObjects) to their respective group, that way if we ever did needed to do something like this, it wouldn't be nearly as painful.
