### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by dpendic** [TheBlackParrot/blockland-preferences#8]
I don't believe it's the project's intention to already include a client for the system. Support_Preferences is supposed to be, well, a Support system for others to build on, not a stand-alone client.

https://github.com/TheBlackParrot/blockland-preferences-client
https://github.com/BlocklandGlass/BlocklandGlass/blob/master/client/GlassPreferencesBridge.cs

Also, in the future be careful with all these sweeping changes. Glass has ~250 users with the old version, and installing the new version would absolutely break the preferences. Keep backwards compatibility in mind, we're working with a relatively live project here.

I'd like us to communicate better as opposed to just suddenly changing everything.

**Comment by TheBlackParrot** [comment]
I could set up an IRC server or something if need be

**Comment by Sixmorphugus** [comment]
I wasn't aware this script had already been adopted. My apologies for the many lines of mod code you'll now have to rewrite.

Also, client was only there for testing. Have now removed it.
